### ISSUE TITLE
Demo build dependency failure: haskell-src-exts

### ISSUE THREAD

**Issue by BigMassive** [deepfire/reflex-glfw#9]
I'm a total noob with nix, reflex and reflex-glfw (thanks for sharing).  Following: `nix-shell --no-build-output`, I received a build error about a missing dependency:
>   Configuring reflex-0.5.0...
>   Setup: Encountered missing dependencies:
>   haskell-src-exts >=1.16 && <1.20

Hackage shows that package is currently at version 1.20.2.  Is there an easy way for me to sort this or does this require a bump elsewhere?

**Comment by deepfire-pusher** [comment]
@BigMassive, I've bumped `reflex` to a newer version that shouldn't have this problem -- and also made it ignore version constraints.

Please yell if this doesn't help!
